### ISSUE TITLE
考研篇催更！A佬好多帖子都404了

### ISSUE THREAD

**Issue by langtaomv** [Anticorianderist/kaoyan#1]
![image](https://user-images.githubusercontent.com/85921722/211328819-04687e41-7ba2-4ab8-9c5f-6d01c6be4b60.png)

**Comment by Anticorianderist** [comment]
收到。催更有效，周末写完。

**Comment by Paul-220** [comment]
求更新 21年考研期间偶然在知乎，刷到博主。感触良多，说了许多的具有可操作性的东西，现在研一下学期突然发现自己跟博主之前记录的大一大二一样，每天昏昏沉沉不知道做什么。向再去知乎吸取吸取经验，找找方向，结果没了。博主多更新啊，之前好多帖子都没了，哭泣。

**Comment by Anticorianderist** [comment]
> 求更新 21年考研期间偶然在知乎，刷到博主。感触良多，说了许多的具有可操作性的东西，现在研一下学期突然发现自己跟博主之前记录的大一大二一样，每天昏昏沉沉不知道做什么。向再去知乎吸取吸取经验，找找方向，结果没了。博主多更新啊，之前好多帖子都没了，哭泣。

除了一些碎碎念的知乎想法，以前的文章或高赞文章都放在GitHub/Anticorianderist/blog里了。

催更有效。从本周开始，大约每周末更新几千字。
