### ISSUE TITLE
举手！

### ISSUE THREAD

**Issue by 001klein** [Anticorianderist/kaoyan#3]
博主说的那段“远超上交计算机硕士学位财富经历”的旧文还能看到吗

**Comment by Anticorianderist** [comment]
> 博主说的那段“远超上交计算机硕士学位财富经历”的旧文还能看到吗

那篇是曾经的一个知乎回答。我删除了所有知乎回答并注销了账号，所以看不到了。其实那段经历只是跨越了个人成长的一个里程碑，倒也不至于发生了那段经历便如何如何。它之所以重于上交计算机硕士学位，仅仅是因为随便拎点什么经历出来也强于上交计算机硕士学位。

**Comment by 001klein** [comment]
我是从知乎来的，暑假那段时间在忙看知乎少，最后只来得及看到“退乎”那篇文章。还好看到了你在github，很可惜没有保存，我觉得学长你的回答都值得看。谢谢回复

**Comment by 001klein** [comment]
我好奇心的出发点主要在于是情感经历，发生了那段经历便跨过人生成长的一个里程碑就已经很有价值了，并且是学长你的思考和总结。对跟一个连暧昧也许都算不上的女孩子近距离相处24天，不再发晚安两个月，留念8个月甚至会更久的情场新人我来说。

顺便在评论一下，
“以一个学习者的身份，学好知识顺便拿高分。”
“随便拎点什么经历出来也强于上交计算机硕士学位。”
给这两个观点点赞

**Comment by Anticorianderist** [comment]
> 我好奇心的出发点主要在于是情感经历，发生了那段经历便跨过人生成长的一个里程碑就已经很有价值了，并且是学长你的思考和总结。对跟一个连暧昧也许都算不上的女孩子近距离相处24天，不再发晚安两个月，留念8个月甚至会更久的情场新人我来说。
> 
> 顺便在评论一下， “以一个学习者的身份，学好知识顺便拿高分。” “随便拎点什么经历出来也强于上交计算机硕士学位。” 给这两个观点点赞

感情经历倒不是那个里程碑的重点，主要是因为当初表白和写情书引出了从小到大独自振翅高飞的苦水吧。至于异性关系，以你的描述，如果想脱单，我建议你变帅；如果想拥有高质量的恋爱关系，我建议你变得“自信、强大、深情”。我自认为我相当了解普通男性这个群体，但这个时代对于普通男性过于残忍了。

很多偏宏观的叙述和结论，三言两语是说不清楚的。对于你可能从我这里获得什么有益于你的信息，我的建议是：试着读出一篇文章的脉络和核心结论。假如我在某些方面只言片语地带过或者留白，说明我暂时没有时间精力或者能力写好，默认原文的立场或者观点，继续往下读就行了。异性关系是非常复杂的话题，在写完《新生》以及经济能力过关之后，我也会大写特写的。但就男生的性吸引力来说，变帅、自信、强大、深情这类努力的方向和优先级，几乎是随处可见的共识。

**Comment by 001klein** [comment]
> > 我好奇心的出发点主要在于是情感经历，发生了那段经历便跨过人生成长的一个里程碑就已经很有价值了，并且是学长你的思考和总结。对跟一个连暧昧也许都算不上的女孩子近距离相处24天，不再发晚安两个月，留念8个月甚至会更久的情场新人我来说。
> > 
> > 顺便在评论一下， “以一个学习者的身份，学好知识顺便拿高分。” “随便拎点什么经历出来也强于上交计算机硕士学位。” 给这两个观点点赞
> 
> 感情经历倒不是那个里程碑的重点，主要是因为当初表白和写情书引出了从小到大独自振翅高飞的苦水吧。至于异性关系，以你的描述，如果想脱单，我建议你变帅；如果想拥有高质量的恋爱关系，我建议你变得“自信、强大、深情”。我自认为我相当了解普通男性这个群体，但这个时代对于普通男性过于残忍了。
> 
> 很多偏宏观的叙述和结论，三言两语是说不清楚的。对于你可能从我这里获得什么有益于你的信息，我的建议是：试着读出一篇文章的脉络和核心结论。假如我在某些方面只言片语地带过或者留白，说明我暂时没有时间精力或者能力写好，默认原文的立场或者观点，继续往下读就行了。异性关系是非常复杂的话题，在写完《新生》以及经济能力过关之后，我也会大写特写的。但就男生的性吸引力来说，变帅、自信、强大、深情这类努力的方向和优先级，几乎是随处可见的共识。

明白了，谢谢。

不过也许在文章里您不经意间的某一句话，对我来说却能很有触动，比如“不甘心只作为下一代的养料而存在”这句，也是我见识尚浅，我是第一次看到这句话，忽然想到自己的家庭，简单的比喻实在让我震撼了几分钟。当然这和您的建议不冲突。

**Comment by langtaomv** [comment]
哈哈，我也对于佬这段财富经历很感兴趣，不知道是什么项目？

**Comment by Anticorianderist** [comment]
> 哈哈，我也对于佬这段财富经历很感兴趣，不知道是什么项目？

https://geo.jlu.edu.cn/info/1093/12886.htm
