### ISSUE TITLE
考研英语の词典

### ISSUE THREAD

**Issue by Anticorianderist** [Anticorianderist/kaoyan#4]
> 链接：https://pan.baidu.com/s/1RWvdhGfQlT7p80yfWxjUjg 
> 提取码：qwer
> （此链接有效期至2023-10-25）

请长期使用百度网盘的同学转存一份，并将分享链接（有效期：永久）发在这个issue下。万分感谢！

PS：对于repo的问题，发起issue应该是最高效的方式。我不一定每天查看Gmail；小蓝鸟的敏感账号、通知、私信、回复可见性似乎有点问题（比如我不知道私信是否发送成功、对方和自己的回复可见性），所以可能连简单的异步通信都有些毛病。

**Comment by KKK0123456789** [comment]
通过百度网盘分享的文件：Dictiona…
链接:https://pan.baidu.com/s/1lxbmaRBKqYHTVF7L0cGcKg?pwd=m3rn 
提取码:m3rn
复制这段内容打开「百度网盘APP 即可获取」

**Comment by Anticorianderist** [comment]
> 通过百度网盘分享的文件：Dictiona… 链接:[https://pan.baidu.com/s/1lxbmaRBKqYHTVF7L0cGcKg?pwd=m3rn ](https://pan.baidu.com/s/1lxbmaRBKqYHTVF7L0cGcKg?pwd=m3rn%C2%A0) 提取码:m3rn 复制这段内容打开「百度网盘APP 即可获取」

❤️❤️❤️

**Comment by langtaomv** [comment]
谢谢a佬，今天有啦^_^
