### ISSUE TITLE
关于复试技巧

### ISSUE THREAD

**Issue by SchweitzerGAO** [Anticorianderist/kaoyan#5]
学长您好，在github上看到您这个repo，我受益匪浅。我也是今年二战，去年是在复试面试阶段折戟。想请问一下学长复试有什么技巧，以及有无必要现在联系意向导师呢？

**Comment by Anticorianderist** [comment]
复试是因学校而异的，而且有点看运气。至于一些比较普适性的理解和建议，下下篇就可以写到复试了，不用急。

联系导师：如果你没有明确的加分项（比如你是本校本专业的、你特别了解对方），我建议不要联系。什么时候分别怎么联系导师，这个我下下下周也会写。

但是，我建议你继续把初试刷高（除非你觉得自己没有提升空间了），不要主动摄入和复试、导师的信息。这个完全可以在初试结束之后再开始。现在想这些徒增烦恼，而且没有用。

**Comment by SchweitzerGAO** [comment]
好的，谢谢学长，我明白该怎么做了
