### ISSUE TITLE
1-2-08编号0x02重复

### ISSUE THREAD

**Issue by SchweitzerGAO** [Anticorianderist/kaoyan#6]
[这篇文章](https://github.com/Anticorianderist/kaoyan/blob/main/1-src/2-essays/8-second-exam.md)0x02编号重复了

**Comment by Anticorianderist** [comment]
> [这篇文章](https://github.com/Anticorianderist/kaoyan/blob/main/1-src/2-essays/8-second-exam.md)0x02编号重复了

已改正。
