### ISSUE TITLE
通用的学习模式和学习理念

### ISSUE THREAD

**Issue by Yancey597** [Anticorianderist/kaoyan#8]
[上篇：初试方法论/4 计算机学科专业基础综合](https://github.com/Anticorianderist/kaoyan/blob/main/1-src/1-methodologies/4-408.md)

中提到：王道单科书相配套的学习模式是错题本；真题相配套的学习模式是总结。一些通用的学习模式和学习理念，我将在考研杂谈篇中详述。

在考研杂谈中好像没有对应的内容耶🥹

**Comment by Anticorianderist** [comment]
感谢你的反馈。我会在未来的两个月中整理好这个repo，比如你所提到的前后不照应，以整体自洽。

放心。既然你提到了，之后肯定就会有了！

**Comment by Yancey597** [comment]
好的，感谢回复
